# This workflow build and push a Docker container to Google Artifact Registry and deploy it on Cloud Run when a commit is pushed to the "main" branch
#
# Overview:
# 1. Authenticate to Google Cloud
# 2. Authenticate Docker to Artifact Registry
# 3. Build a docker container
# 4. Publish it to Google Artifact Registry
# 5. Deploy it to Cloud Run

name: Build and Deploy Machine Learning APIs to Cloud Run

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

env:
  PROJECT_ID: sewain-405712
  GAR_LOCATION: asia-southeast1
  SERVICE: image-classification-api
  REGION: asia-southeast2

jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.SA_CREDS }}'

      - name: Build and Push Container
        run: |-
          echo '${{ secrets.SA_CREDS }}' > /tmp/account.json
          gcloud auth activate-service-account --key-file=/tmp/account.json
          gcloud auth configure-docker asia-southeast1-docker.pkg.dev --quiet
          docker build -t "asia-southeast1-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ secrets.GAR_REPO }}/machine-learning-api:${{ github.sha }}" ./
          docker push "asia-southeast1-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ secrets.GAR_REPO }}/machine-learning-api:${{ github.sha }}"

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          image: 'asia-southeast1-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ secrets.GAR_REPO }}/machine-learning-api:${{ github.sha }}'
          flags: '--allow-unauthenticated --vpc-connector sewain-be'

      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}
